### ISSUE TITLE
Undefined method "decode" in calendar?

### ISSUE THREAD

**Issue by apollolux** [rjorgenson/geeklet-scripts#3]
Hi, I wanted to set up the calendar.rb script as a geeklet but I get the following error:

`calendar.rb:271:in '<main>': undefined method 'decode' for nil:NilClass (NoMethodError)`

I would do a correction as a pull request but I unfortunately don't know ruby :/

Running Geektool 3.1.8 on Mavericks 10.9.5, ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]

**Comment by rjorgenson** [comment]
HI Apollolux,

The latest version of calendar.rb uses the htmlentities gem to generate html output for use with Ubersicht. I thought I documented this but it doesn't appear I did, I will do that in the README, thanks!
