### ISSUE TITLE
Undefined method decode in calender.rb

### ISSUE THREAD

**Issue by lenusmars** [rjorgenson/geeklet-scripts#4]
If you don't activate the html option you get the method error on 271 because the encode variable is defined in an if block near the top only if the html option is chosen. Unfortunately you still need it to interpret line seperator A. 

Reassigning the encode variable outside the if block fixed the issue.

**Comment by rjorgenson** [comment]
Thanks for reporting this @lenusmars! Fix pushed to master in 3fd87f6
